
default['tomcat']['home'] = '/opt/tomcat'
default['tomcat']['base'] = '/opt/tomcat'
default['tomcat']['version'] = '8.5.33'
default['tomcat']['native']['home'] = '/opt/tomcat/native'
default['tomcat']['native']['version'] = '1.2.17'
default['tomcat']['apr']['home'] = '/opt/tomcat/native'
default['tomcat']['apr']['version'] = '1.6.3'
default['tomcat']['java']['home'] = '/opt/jdk1.8.0_181'
default['tomcat']['java']['version'] = '8u181'
default['tomcat']['appname'] = 'Tomcat'
default['tomcat']['user'] = 'tomcat'
default['tomcat']['password'] = 'tomcat'
default['tomcat']['longappname'] = 'Tomcat Web Service'
